id: I9422BC4A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T07:33:09+00:00'
last_modified: '2022-06-08T17:14:07.212194+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG14623
  title: ཕྱི་མ་རྒྱུད་ཀྱི་འགྲེལ་བ་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4BEC:
      image_group_id: I1KG15635
      title: ''
      total_pages: 538
      order: 1
      base_file: 4BEC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
